/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import org.junit.jupiter.api.Test;

import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
    public void testSetAndGet() {
        HashTable<String, Integer> ht = new HashTable<>();

        ht.set("Alice", 25);
        ht.set("Bob", 30);

        assertEquals(Integer.valueOf(25), ht.get("Alice"));
        assertEquals(Integer.valueOf(30), ht.get("Bob"));
    }

    @Test
    public void testSetExistingKey() {
        HashTable<String, Integer> ht = new HashTable<>();

        ht.set("Alice", 25);
        ht.set("Alice", 30);

        assertEquals(Integer.valueOf(30), ht.get("Alice"));
    }

    @Test
    public void testHas() {
        HashTable<String, Integer> ht = new HashTable<>();

        ht.set("Alice", 25);
        ht.set("Bob", 30);

        assertTrue(ht.has("Alice"));
        assertTrue(ht.has("Bob"));
        assertFalse(ht.has("Eve"));
    }

    @Test
    public void testKeys() {
        HashTable<String, Integer> ht = new HashTable<>();

        ht.set("Alice", 25);
        ht.set("Bob", 30);

        assertEquals(2, ht.keys().size());
        assertTrue(ht.keys().contains("Alice"));
        assertTrue(ht.keys().contains("Bob"));
    }

    @Test
    public void repeatedWord(){
        HashTable<String, Integer> hashTable = new HashTable<String, Integer>();

        String sentence1 = "Once upon a time, there was a brave princess who...";
        String sentence2 = "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only...";
        String sentence3 = "It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York...";

        String test1 = hashTable.hashmapRepeatedWord(sentence1);
        String test2 = hashTable.hashmapRepeatedWord(sentence2);
        String test3 = hashTable.hashmapRepeatedWord(sentence3);

        assertEquals("a", test1, "repeatedWord test should return 'a'");
        assertEquals("it", test2, "repeatedWord test should return 'it'");
        assertEquals("summer", test3, "repeatedWord test should return 'summer'");
    }

    @Test
    public void testTreeIntersectionWithCommonValues() {

        BinaryTree<Integer> tree1 = new BinaryTree<>(1);
        tree1.left = new BinaryTree<>(2);
        tree1.right = new BinaryTree<>(3);
        tree1.left.left = new BinaryTree<>(4);
        tree1.left.right = new BinaryTree<>(5);
        BinaryTree<Integer> tree2 = new BinaryTree<>(3);
        tree2.left = new BinaryTree<>(5);
        tree2.right = new BinaryTree<>(6);
        tree2.left.left = new BinaryTree<>(4);
        TreeIntersection<Integer> treeIntersection = new TreeIntersection<>();
        Set<Integer> result = treeIntersection.tree_intersection(tree1, tree2);
        assertEquals(3, result.size());
        assertTrue(result.contains(3));
        assertTrue(result.contains(4));
        assertTrue(result.contains(5));
    }

}

