/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
    public void testSetAndGet() {
        HashTable<String, Integer> ht = new HashTable<>();

        ht.set("Alice", 25);
        ht.set("Bob", 30);

        assertEquals(Integer.valueOf(25), ht.get("Alice"));
        assertEquals(Integer.valueOf(30), ht.get("Bob"));
    }

    @Test
    public void testSetExistingKey() {
        HashTable<String, Integer> ht = new HashTable<>();

        ht.set("Alice", 25);
        ht.set("Alice", 30);

        assertEquals(Integer.valueOf(30), ht.get("Alice"));
    }

    @Test
    public void testHas() {
        HashTable<String, Integer> ht = new HashTable<>();

        ht.set("Alice", 25);
        ht.set("Bob", 30);

        assertTrue(ht.has("Alice"));
        assertTrue(ht.has("Bob"));
        assertFalse(ht.has("Eve"));
    }

    @Test
    public void testKeys() {
        HashTable<String, Integer> ht = new HashTable<>();

        ht.set("Alice", 25);
        ht.set("Bob", 30);

        assertEquals(2, ht.keys().size());
        assertTrue(ht.keys().contains("Alice"));
        assertTrue(ht.keys().contains("Bob"));
    }
}

