/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedlist;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    private LinkedList<Integer> testList;
    @Test
    public void testEmptyLinkedList() {
        LinkedList<Integer> testList = new LinkedList<>();
        assertNotNull(testList);
    }

    @Test
    public void testInsert(){
        testList = new LinkedList<>();
        testList.insert(5);
        assertNotNull(testList);

    }
    @Test
    public void testIsIncludedFalse(){
        testList = new LinkedList<>();
        testList.insert(5);
        assertEquals(false, testList.include(50));
    }


    @Test
    public void testIsIncludedTrue(){
        testList = new LinkedList<>();
        testList.insert(5);
        testList.insert(6);
        assertTrue(testList.include(6));
    }
    @Test
    public void testToString(){
        testList = new LinkedList<>();
        testList.insert(5);
        testList.insert(6);
        assertEquals("{6} -> {5} -> Null", testList.toString());
    }

}