/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stackandqueue;

import org.junit.jupiter.api.Test;
import sort.InsertionSort;

import static org.junit.jupiter.api.Assertions.*;

class SortTest {

    int[] intArray = new int[]{ 8,4,23,24,16};

    @Test
    void InsertionSortTest(){

        InsertionSort sort =new InsertionSort();
        sort.InsertionSort(intArray);
        String str ="";
        for (int num: intArray) {
            str+=num+",";
        }
        assertEquals("4,8,16,23,24,",str);
    }


    }

