/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    private Stack<Integer> stack;

    @Test void testStackPush() {
        stack = new Stack<Integer>();
        stack.push(5);
        assertEquals("Top -> {5} -> Null", stack.toString());
        assertEquals(1, stack.getSize());
        stack.push(6);
        stack.push(7);
        stack.push(8);
        assertEquals("Top -> {8} -> {7} -> {6} -> {5} -> Null", stack.toString());
        assertEquals(4, stack.getSize());
    }

    @Test void testStackPop() {
        stack = new Stack<Integer>();
        stack.push(5);
        stack.push(6);
        stack.push(7);

        assertEquals(7, stack.pop());
        assertEquals(2, stack.getSize());


        assertEquals(6, stack.pop());
        assertEquals(1, stack.getSize());

        assertEquals(5, stack.pop());
        assertEquals(0, stack.getSize());
    }

    @Test void testStackPeek() throws Exception {
        stack = new Stack<Integer>();
        stack.push(5);
        stack.push(6);
        assertEquals(6, stack.peek());
    }
    private PseudoQueue<Integer> pq;

    @Test void testEnqueue(){
        pq = new PseudoQueue<Integer>();
        pq.enqueue(1);
        pq.enqueue(2);
        pq.enqueue(3);
        assertEquals("Top -> {1} -> {2} -> {3} -> Null", pq.toString());
    }

    @Test void testDequeue(){
        pq = new PseudoQueue<Integer>();
        pq.enqueue(1);
        pq.enqueue(2);
        pq.enqueue(3);
        pq.dequeue();
        assertEquals("Top -> {2} -> {3} -> Null", pq.toString());
        pq.dequeue();
        pq.dequeue();
        assertEquals("Your List Is Empty", pq.toString());
    }

}

