/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedlist;

public class App {

    static final LinkedList<Integer> list1 = new LinkedList<>();
    public static void main(String[] args) {
        list1.insert(1);
        list1.insert(2);
        list1.insert(3);
        list1.insert(2);
        list1.insert(1);




    }


}