/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedlist;

public class App {

    static final LinkedList<Integer> list1 = new LinkedList<>();
    public static void main(String[] args) {
//        LinkedList<Integer> myList = new LinkedList<>();
//
//        myList.append(1);
//        myList.append(2);
//        myList.append(3);
//
//        System.out.println("After appending:");
//        System.out.println(myList);
//
//        myList.insertBefore(2, 5);
//        myList.insertBefore(1, 0);
//
//        System.out.println("After inserting before:");
//        System.out.println(myList);
//
//        myList.insertAfter(2, 6);
//        myList.insertAfter(3, 7);
//
//        System.out.println("After inserting after:");
//        System.out.println(myList);

        LinkedList  testList1 = new LinkedList<>();
        LinkedList testList2 = new LinkedList<>();
        LinkedList  mergedList = new LinkedList<>();

        testList1.append(1);
        testList1.append(3);
        testList1.append(5);

        testList2.append(2);
        testList2.append(4);
        testList2.append(6);
        System.out.println(mergedList);
    }
}