/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedlist;

public class App {

    static final LinkedList<Integer> list1 = new LinkedList<>();
    public static void main(String[] args) {
        LinkedList<Integer> myList = new LinkedList<>();

        myList.append(1);
        myList.append(2);
        myList.append(3);

        System.out.println("After appending:");
        System.out.println(myList);

        myList.insertBefore(2, 5);
        myList.insertBefore(1, 0);

        System.out.println("After inserting before:");
        System.out.println(myList);

        myList.insertAfter(2, 6);
        myList.insertAfter(3, 7);

        System.out.println("After inserting after:");
        System.out.println(myList);



    }


}